"""Persistence contract for Sales Orders."""

from typing import Protocol
from uuid import UUID

from phoenix_sales.domain.sales_order import SalesOrder


class SalesOrderRepository(Protocol):
    def save(self, order: SalesOrder) -> SalesOrder: ...
    def get(self, tenant_id: str, order_id: UUID) -> SalesOrder | None: ...
    def list_by_customer(self, tenant_id: str, customer_id: str) -> list[SalesOrder]: ...
    def list_by_quote(self, tenant_id: str, quote_id: UUID) -> list[SalesOrder]: ...
    def list_by_opportunity(self, tenant_id: str, opportunity_id: UUID) -> list[SalesOrder]: ...
    def delete(self, tenant_id: str, order_id: UUID) -> None: ...
